version: '3.8'
services:
  vue-app:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_FORCE_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn install && yarn dev"
