version: '3.8'
services:
  vue-app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev
